version: '3'

services:
  db: 
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_USER: prisma
      MYSQL_DATABASE: nestjs
      MYSQL_PASSWORD: 54321
      MYSQL_ROOT_PASSWORD: 54321
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  cache:
    image: redis
    ports:
      - 6379:6379